### ISSUE TITLE
Trash datasets and machine learning models

### ISSUE THREAD

**Issue by HamidiMassinissa** [institut-galilee/2020-Karadik#1]
Don't know if you have already explored this particular aspect but here is a repository that provides with a dataset and a learning model https://github.com/garythung/trashnet.
It is worth noting that the model is built using Torch rather than Tensorflow but the translation is straightforward.

**Comment by Nady95** [comment]
Yep, that's the dataset we are currently using ! :)
However, we are using [this model](https://github.com/antiplasti/Plastic-Detection-Model) which is built using Tensorflow, and until now it's worked pretty well on a computer (haven't tested yet on a Raspberry Pi). We are also planning to add more photos to this dataset to maximize the recognition rate.

Thanks for your comment,
The Karadik Team
